# Generated by Django 2.2.22 on 2021-05-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(choices=[('SqFt', 'Square foots')], default='SqFt', max_length=4)),
                ('bathrooms', models.FloatField(null=True)),
                ('bedrooms', models.IntegerField()),
                ('home_size', models.IntegerField(null=True)),
                ('home_type', models.CharField(choices=[('SingleFamily', 'Single Family'), ('VacantResidentialLand', 'Vacant Residential Land'), ('Miscellaneous', 'Miscellaneous'), ('MultiFamily2To4', 'MultiFamily2To4'), ('Condominium', 'Condominium'), ('Apartment', 'Apartment'), ('Duplex', 'Duplex')], default='SingleFamily', max_length=30)),
                ('last_sold_date', models.DateField(null=True)),
                ('last_sold_price', models.FloatField(null=True)),
                ('link', models.URLField()),
                ('price', models.FloatField()),
                ('property_size', models.IntegerField(null=True)),
                ('rent_price', models.FloatField(null=True)),
                ('rentzestimate_amount', models.FloatField(null=True)),
                ('rentzestimate_last_updated', models.DateField(null=True)),
                ('tax_value', models.FloatField()),
                ('tax_year', models.IntegerField()),
                ('year_built', models.IntegerField(null=True)),
                ('zestimate_amount', models.FloatField(null=True)),
                ('zestimate_last_updated', models.DateField(null=True)),
                ('zillow_id', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=5)),
            ],
        ),
    ]
